#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[user]
name = "Ahmed El Gabri"
email = "ahmed@gabri.me"

[ui]
default-command = "log"
# https://difftastic.wilfred.me.uk/jj.html
# diff-formatter = ["difft", "--color=always", "$left", "$right"]

[revsets]
log = "present(@) | ancestors(immutable_heads().., 10) | present(trunk())"
